CREATE TABLE TBL_PRODUCTO(
    PRODUCTO_ID NUMERIC(8) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(360) NOT NULL,
    PRECIO NUMERIC (6,2) NOT NULL,
    CANTIDAD NUMERIC (6,2) NOT NULL,
    GARANTIA VARCHAR2(20) NULL
);

CREATE SEQUENCE SEQ_PRODUCTO;

INSERT INTO TBL_PRODUCTO(PRODUCTO_ID,NOMBRE,PRECIO,CANTIDAD,GARANTIA)
VALUES(SEQ_PRODUCTO.NEXTVAL ,'Dogxtreme Adulto Salmón Alimento Seco Perro 12 KG',199.90,10,'100%');

COMMIT;

SELECT PRODUCTO_ID,NOMBRE,PRECIO,GARANTIA FROM TBL_PRODUCTO;


CREATE TABLE TBL_CLIENTE(
    CLIENTE_ID INT NOT NULL PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(260) NOT NULL UNIQUE,
    RUC CHAR(11) NOT NULL UNIQUE,
    DIRECCION VARCHAR2(400) NOT NULL,
    TELEFONO VARCHAR2(20) NULL,
    CORREO VARCHAR2(60) NULL,
    ESTADO CHAR(1) DEFAULT '1' NOT NULL 
);

CREATE SEQUENCE SEQ_CLIENTE;

INSERT INTO TBL_CLIENTE(CLIENTE_ID,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO)
VALUES(SEQ_CLIENTE.NEXTVAL,'CLARO EMPRESAS','20544987258','AV. LARCO 237-SAN ISIDRO','456-4574','CONTACTO@CLARO.COM.PE');

COMMIT;

SELECT CLIENTE_ID,RAZON_SOCIAL,RUC,DIRECCION,TELEFONO,CORREO, ESTADO FROM TBL_CLIENTE;

CREATE TABLE TBL_CATEGORIA(
    CATEGORIA_ID INT NOT NULL PRIMARY KEY ,
    NOMBRE_CORTO VARCHAR2(60) NOT NULL,
    NOMBRE_LARGO VARCHAR2(260) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_CATEGORIA;

INSERT INTO TBL_CATEGORIA (CATEGORIA_ID, NOMBRE_CORTO,NOMBRE_LARGO)
VALUES(SEQ_CATEGORIA.NEXTVAL,'EQP-COMP','Equipo de cómputo');
INSERT INTO TBL_CATEGORIA (CATEGORIA_ID, NOMBRE_CORTO,NOMBRE_LARGO)
VALUES(SEQ_CATEGORIA.NEXTVAL,'LIMP-COMP','Limpieza de cómputo');


COMMIT;

SELECT CATEGORIA_ID, NOMBRE_CORTO,NOMBRE_LARGO,ESTADO FROM TBL_CATEGORIA;

ALTER TABLE TBL_PRODUCTO
ADD CATEGORIA_ID INT NULL REFERENCES TBL_CATEGORIA (CATEGORIA_ID) ;

ALTER TABLE TBL_PRODUCTO
ADD CANTIDAD INT NULL ;

SELECT PRODUCTO_ID, NOMBRE,PRECIO,CANTIDAD,ESTADO,CATEGORIA_ID FROM TBL_PRODUCTO;


CREATE TABLE TBL_PEDIDO_CAB(
    PEDIDO_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    CLIENTE_ID NUMERIC(6) NOT NULL REFERENCES TBL_CLIENTE(CLIENTE_ID),
    VENDEDOR_ID NUMERIC(6) NULL REFERENCES TBL_VENDEDOR(VENDEDOR_ID),
    GLOSA VARCHAR2(240) NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    
    SUB_TOTAL NUMERIC(9,2) NOT NULL,
    IGV NUMERIC(9,2) NOT NULL,
    TOTAL NUMERIC(9,2) NOT NULL,
    
    SITUACION_ID NUMERIC(6)NOT NULL REFERENCES TBL_SITUACION(SITUACION_ID),

    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);


CREATE TABLE TBL_PEDIDO_DET(
    PEDIDO_DET_ID NUMERIC(6) NOT NULL PRIMARY KEY,
    PEDIDO_ID NUMERIC(6) REFERENCES TBL_PEDIDO_CAB(PEDIDO_ID),
    PRODUCTO_ID NUMERIC(6)NOT NULL REFERENCES TBL_PRODUCTO(PRODUCTO_ID),
    CANTIDAD NUMERIC(6) NOT NULL,
    PRECIO NUMERIC(6,2) NOT NULL,
    
    SUB_TOTAL NUMERIC(9,2) NOT NULL,
    IGV NUMERIC(9,2) NOT NULL,
    TOTAL NUMERIC(9,2) NOT NULL,
        
    ESTADO CHAR(1) DEFAULT '1' NOT NULL
);


CREATE TABLE TBL_SITUACION(
    SITUACION_ID INT NOT NULL PRIMARY KEY ,
    NOMBRE_CORTO VARCHAR2(60) NOT NULL,
    NOMBRE_LARGO VARCHAR2(260) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_SITUACION;

INSERT INTO TBL_SITUACION (SITUACION_ID, NOMBRE_CORTO,NOMBRE_LARGO)
VALUES(SEQ_SITUACION.NEXTVAL,'REG','Registrado');
INSERT INTO TBL_SITUACION (SITUACION_ID, NOMBRE_CORTO,NOMBRE_LARGO)
VALUES(SEQ_SITUACION.NEXTVAL,'OBS','Observado');
INSERT INTO TBL_SITUACION (SITUACION_ID, NOMBRE_CORTO,NOMBRE_LARGO)
VALUES(SEQ_SITUACION.NEXTVAL,'ANU','Anulado');


CREATE TABLE TBL_PAIS(
    PAIS_ID INT NOT NULL PRIMARY KEY ,
    NOMBRE VARCHAR2(160) NOT NULL,
    ISO_2 VARCHAR2(20) NOT NULL,
    ISO_3 VARCHAR2(20) NOT NULL,
    CODIGO VARCHAR2(20) NOT NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_PAIS;

INSERT INTO TBL_PAIS (PAIS_ID, NOMBRE,ISO_2,ISO_3,CODIGO)
VALUES(SEQ_SITUACION.NEXTVAL,'Afganistán','AF','AFG',93);
INSERT INTO TBL_PAIS (PAIS_ID, NOMBRE,ISO_2,ISO_3,CODIGO)
VALUES(SEQ_SITUACION.NEXTVAL,'Perú','PE','PER',51);
INSERT INTO TBL_PAIS (PAIS_ID, NOMBRE,ISO_2,ISO_3,CODIGO)
VALUES(SEQ_SITUACION.NEXTVAL,'México','MX','MEX',52);
COMMIT;

ALTER TABLE TBL_CLIENTE
ADD PAIS_ID INT NULL REFERENCES TBL_PAIS (PAIS_ID) ;


CREATE TABLE TBL_VENDEDOR(
    VENDEDOR_ID INT NOT NULL PRIMARY KEY ,
    APELLIDO_PATERNO VARCHAR2(60) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(60) NOT NULL,
    NOMBRE VARCHAR2(60) NOT NULL,
    
    DIRECCION VARCHAR2(400) NOT NULL,
    TELEFONO VARCHAR2(20) NULL,
    CORREO VARCHAR2(60) NULL,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_VENDEDOR;

INSERT INTO TBL_PEDIDO_CAB(PEDIDO_ID,CLIENTE_ID,VENDEDOR_ID,GLOSA,SUB_TOTAL,IGV,TOTAL,SITUACION_ID) 
VALUES(SEQ_PEDIDO_CAB.NEXTVAL, 1,1,'Dogxtreme y correa - Juan Pablo', 1799.10,323.84,2122.94,1);
COMMIT;
 	  	  

INSERT INTO TBL_PEDIDO_DET(PEDIDO_DET_ID,PEDIDO_ID,PRODUCTO_ID,CANTIDAD,PRECIO,SUB_TOTAL,IGV,TOTAL) 
VALUES(SEQ_PEDIDO_DET.NEXTVAL, 1,1,5,199.9, 999.50, 179.91,1179.41);
COMMIT;
  	  	  	  
INSERT INTO TBL_PEDIDO_DET(PEDIDO_DET_ID,PEDIDO_ID,PRODUCTO_ID,CANTIDAD,PRECIO,SUB_TOTAL,IGV,TOTAL) 
VALUES(SEQ_PEDIDO_DET.NEXTVAL, 1,8,4,50, 200.00, 36.00,236.00 );
COMMIT;
  	  	 


SELECT * FROM TBL_PRODUCTO;
SELECT * FROM TBL_PEDIDO_CAB;
SELECT * FROM TBL_PEDIDO_DET;



